version: "3"
services:
    whatsapp-chatgpt:
        image: ghcr.io/askrella/whatsapp-chatgpt:master
        environment:
            OPENAI_API_KEY: "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"
            OPENAI_GPT_MODEL: "gpt-3.5-turbo"
            PREFIX_ENABLED: "true"
            SERPAPI_API_KEY: ""
        volumes:
            - session-data:/app/session
volumes:
    session-data:
